# config

# interval in mins
interval: 35

accounts:
  - username: "123A01012000"
    password: "114514"

booking:
  want_sessions: [1,2,3,4,5,6,7,8]
  want_months: ["202211", "202212"]

telegram:
  enabled: true
  token: "5123456789:asdfghjkl"
  chat_id: "512345678"
