# config

# interval in mins
interval: 35

accounts:
  - username: "123A01012000"
    password: "114514"
    preferred_slots:
    - date: "2022-11-11"
      sessions: [1,2,3]
    - date: "2022-12-12"
      sessions: [4,5,6]

booking:
  query_months: ["202211", "202212"]

telegram:
  enabled: true
  token: "5123456789:asdfghjkl"
  broadcast_chat_id: "512345678"
